name: Ubuntu20.04, ROS2 Continuous Integration

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - ros_version: "humble"
            ubuntu_version: "ubuntu-22.04"
          - ros_version: "iron"
            ubuntu_version: "ubuntu-22.04"
    runs-on: ${{ matrix.ubuntu_version }}
    steps:
      #
      # Setup the machines and build environment
      #
      - name: Install ROS.
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: ${{ matrix.ros_version }}

      #
      # Checkout the current branch
      #
      - uses: actions/checkout@v4

      #
      # Use the .repos inside the cloned repository.
      #
      - run: |
          ll -R ../
          cp ../${{ github.event.repository.name }}/.github/workflows/deps.repos /tmp/deps.repos

      #
      # Build and test the repo
      #
      - uses: ros-tooling/action-ros-ci@0.3.14
        with:
          package-name: ${{ github.event.repository.name }}
          target-ros2-distro: ${{ matrix.ros_version }}
          vcs-repo-file-url: /tmp/deps.repos
